const MAX_USERNAME_LENGTH=32;
const MAX_PASSWORD_LENGTH=128;
const MAX_TITLE_LENGTH=200;
const MAX_CONTENT_LENGTH=500000;
const MAX_COMMENT_LENGTH=5000;
const DEFAULT_MODEL='meta/llama-3.3-70b-instruct';
const ROUTER_MODEL='nvidia/gpt-oss-20b';
let tocCache=null,tocCacheAt=0;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, PUT, DELETE, OPTIONS'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8',...CORS}});
const tokenOf=r=>{const a=r.headers.get('Authorization')||'';return a.startsWith('Bearer ')?a.slice(7).trim()||null:null};
const userOf=async(r,e)=>{const t=tokenOf(r);return t?e.DB.prepare('SELECT * FROM users WHERE token=?').bind(t).first():null};
const safeUser=u=>{if(!u)return null;const{password,token,...x}=u;return x};
const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
const makeToken=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
async function sha256(s){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))))}
async function hashPassword(p){const salt=new Uint8Array(16);crypto.getRandomValues(salt);const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},k,256);return `pbkdf2$100000$${hex(salt)}$${hex(new Uint8Array(bits))}`}
async function verifyPassword(p,s){if(typeof s!=='string')return{valid:false,legacy:false};if(s.startsWith('pbkdf2$')){const x=s.split('$');if(x.length!==4||!/^[0-9]+$/.test(x[1])||!/^[0-9a-f]+$/i.test(x[2])||!/^[0-9a-f]+$/i.test(x[3]))return{valid:false,legacy:false};try{const salt=new Uint8Array(x[2].match(/../g).map(v=>parseInt(v,16)));const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:Number(x[1]),hash:'SHA-256'},k,x[3].length*4);return{valid:hex(new Uint8Array(bits)).toLowerCase()===x[3].toLowerCase(),legacy:false}}catch{return{valid:false,legacy:false}}}if(/^[0-9a-f]{64}$/i.test(s))return{valid:(await sha256(p)).toLowerCase()===s.toLowerCase(),legacy:true};return{valid:false,legacy:false}}
async function nim(e,p){const r=await fetch('https://integrate.api.nvidia.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${e.NIM}`,'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw new Error(`NIM ${r.status}: ${await r.text()}`);return r}
async function getToc(e){if(tocCache&&Date.now()-tocCacheAt<3600000)return tocCache;const base=String(e.GH_TEXTBOOK||'').replace(/\/$/,'')+'/';const r=await fetch(base+'toc.json');if(!r.ok)throw new Error(`toc.json HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d)||!d.length)throw new Error('toc.json 格式无效');tocCache=d;tocCacheAt=Date.now();return d}
async function chapter(e,id){const base=String(e.GH_TEXTBOOK||'').replace(/\/$/,'')+'/';const r=await fetch(base+'ch_'+id+'.txt');return r.ok?r.text():null}
async function routeChapter(e,q,toc){const list=toc.map(x=>`${x.id} - ${x.title}`).join('\n');const r=await nim(e,{model:ROUTER_MODEL,messages:[{role:'user',content:`章节目录：\n${list}\n\n用户提问：${q}\n\n只输出最匹配的章节编号（如 003），不要输出其他文字。`}],temperature:0,max_tokens:20,stream:false});const d=await r.json();return String(d?.choices?.[0]?.message?.content||'').match(/\b(\d{3})\b/)?.[1]||null}
const trim=s=>{s=String(s||'');return !s?'（未提供上下文）':s.length<=120000?s:s.slice(85000)+'\n\n[中间内容已截断]\n\n'+s.slice(-35000)};
function sse(up){const{readable,writable}=new TransformStream(),w=writable.getWriter(),r=up.body.getReader(),d=new TextDecoder(),e=new TextEncoder();let b='';(async()=>{try{for(;;){const z=await r.read();if(z.done)break;b+=d.decode(z.value,{stream:true});const ls=b.split('\n');b=ls.pop()||'';for(const line of ls){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(raw==='[DONE]'){await w.write(e.encode('data: {"type":"done"}\n\n'));continue}try{const x=JSON.parse(raw)?.choices?.[0]?.delta;if(x?.reasoning_content)await w.write(e.encode(`data: ${JSON.stringify({type:'reasoning',text:x.reasoning_content})}\n\n`));if(x?.content)await w.write(e.encode(`data: ${JSON.stringify({type:'content',text:x.content})}\n\n`))}catch{}}}}}catch(err){try{await w.write(e.encode(`data: ${JSON.stringify({type:'error',error:err.message||'stream error'})}\n\n`))}catch{}}finally{try{await w.close()}catch{}}})();return readable}
async function chat(b,e){const mode=b?.mode||'note',model=b?.model||DEFAULT_MODEL,msgs=Array.isArray(b?.messages)?b.messages:[],image=typeof b?.image==='string'&&b.image?b.image:null,last=[...msgs].reverse().find(x=>x?.role==='user');if(!last)return json({error:'No user message'},400);let ctx;if(mode==='note')ctx=trim(b.chapterContext);else if(mode==='whiteboard')ctx=trim(b.whiteboardContext);else if(mode==='textbook'){const id=await routeChapter(e,String(last.content||''),await getToc(e));if(!id)return json({error:'未找到相关章节'},404);const t=await chapter(e,id);if(!t)return json({error:`无法获取章节 ${id} 的内容`},404);ctx=trim(t)}else return json({error:'Invalid mode: '+mode},400);const ms=[{role:'system',content:`你是一位生物竞赛辅导老师。严格基于资料回答；资料没有相关信息时明确说明。回答结构清晰、分点阐述，使用中文。\n\n资料内容：\n${ctx}`}];for(const m of msgs.slice(-20))if(m&&['user','assistant'].includes(m.role)&&typeof m.content==='string')ms.push({role:m.role,content:m.content.slice(0,20000)});if(image&&ms.at(-1)?.role==='user')ms.at(-1).content=[{type:'text',text:ms.at(-1).content||'请分析这张图片。'},{type:'image_url',image_url:{url:image}}];const up=await nim(e,{model,messages:ms,temperature:.7,top_p:.95,max_tokens:4096,stream:true,chat_template_kwargs:{enable_thinking:true}});return new Response(sse(up),{headers:{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache','Connection':'keep-alive',...CORS}})}
async function histList(u,e){return await e.COPILOT_HISTORY.get(`histlist_${u.username}`,'json')||[]}
async function history(req,e,u,p,m){if(p==='/api/history'&&m==='GET')return json(await histList(u,e));if(p==='/api/history'&&m==='POST'){const b=await req.json(),messages=Array.isArray(b.messages)?b.messages.slice(-100):[],title=String(b.title||'新对话').slice(0,100),id=Date.now().toString(36)+Math.random().toString(36).slice(2,8),record={id,title,messages,updated_at:new Date().toISOString()};await e.COPILOT_HISTORY.put(`hist_${u.username}_${id}`,JSON.stringify(record));const list=await histList(u,e);await e.COPILOT_HISTORY.put(`histlist_${u.username}`,JSON.stringify([{id,title,updated_at:record.updated_at},...list.filter(x=>x.id!==id)].slice(0,100)));return json({success:true,id})}const z=p.match(/^\/api\/history\/([^/]+)$/);if(!z)return json({error:'Not found'},404);const id=decodeURIComponent(z[1]),key=`hist_${u.username}_${id}`;if(m==='GET')return json(await e.COPILOT_HISTORY.get(key,'json')||{id,messages:[]});if(m==='DELETE'){await e.COPILOT_HISTORY.delete(key);const list=await histList(u,e);await e.COPILOT_HISTORY.put(`histlist_${u.username}`,JSON.stringify(list.filter(x=>x.id!==id)));return json({success:true})}return json({error:'Method not allowed'},405)}
export default{async fetch(req,e){const url=new URL(req.url),p=url.pathname,m=req.method;if(m==='OPTIONS')return new Response(null,{headers:CORS});try{
if(p==='/register'&&m==='POST'){const b=await req.json(),n=typeof b.username==='string'?b.username.trim():'',pw=typeof b.password==='string'?b.password:'';if(!n||!pw)return json({error:'用户名和密码不能为空'},400);if(n.length>MAX_USERNAME_LENGTH)return json({error:`用户名不能超过 ${MAX_USERNAME_LENGTH} 个字符`},400);if(pw.length>MAX_PASSWORD_LENGTH)return json({error:`密码不能超过 ${MAX_PASSWORD_LENGTH} 个字符`},400);if(await e.DB.prepare('SELECT id FROM users WHERE username=?').bind(n).first())return json({error:'用户名已存在'},409);const t=makeToken();await e.DB.prepare('INSERT INTO users (username,password,token,school,honor_year,honor_rank) VALUES (?,?,?,?,?,?)').bind(n,await hashPassword(pw),t,typeof b.school==='string'?b.school.trim():null,typeof b.honor_year==='string'?b.honor_year.trim():null,typeof b.honor_rank==='string'?b.honor_rank.trim():null).run();return json({token:t,username:n})}
if(p==='/login'&&m==='POST'){const b=await req.json(),n=typeof b.username==='string'?b.username.trim():'',pw=typeof b.password==='string'?b.password:'';if(!n||!pw)return json({error:'账号或密码不能为空'},400);const u=await e.DB.prepare('SELECT * FROM users WHERE username=?').bind(n).first();if(!u)return json({error:'账号或密码错误'},401);const c=await verifyPassword(pw,u.password);if(!c.valid)return json({error:'账号或密码错误'},401);if(c.legacy)await e.DB.prepare('UPDATE users SET password=? WHERE id=?').bind(await hashPassword(pw),u.id).run();return json({token:u.token,username:u.username})}
if(p==='/users/me'&&m==='GET'){const u=await userOf(req,e);return u?json({user:safeUser(u)}):json({error:'未登录'},401)}
if(p==='/users/me'&&m==='PUT'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const b=await req.json(),x={};if(b.username!==undefined){const n=String(b.username).trim();if(!n||n.length>MAX_USERNAME_LENGTH)return json({error:'用户名无效'},400);if(n!==u.username&&await e.DB.prepare('SELECT id FROM users WHERE username=? AND id!=?').bind(n,u.id).first())return json({error:'用户名已被占用'},409);x.username=n}for(const k of ['avatar','school','honor_year','honor_rank'])if(b[k]!==undefined)x[k]=typeof b[k]==='string'?b[k].trim():null;if(b.password){if(!b.old_password)return json({error:'修改密码需要提供当前密码'},400);if(!(await verifyPassword(b.old_password,u.password)).valid)return json({error:'当前密码错误'},401);if(String(b.password).length>MAX_PASSWORD_LENGTH)return json({error:'密码不能超过 128 个字符'},400);x.password=await hashPassword(String(b.password));x.token=makeToken()}if(!Object.keys(x).length)return json({error:'没有提供修改字段'},400);await e.DB.prepare(`UPDATE users SET ${Object.keys(x).map(k=>`${k}=?`).join(',')} WHERE id=?`).bind(...Object.values(x),u.id).run();const nn=x.username||u.username;if(nn!==u.username)await e.DB.batch([e.DB.prepare('UPDATE posts SET author=? WHERE author=?').bind(nn,u.username),e.DB.prepare('UPDATE comments SET username=? WHERE username=?').bind(nn,u.username)]);const fresh=await e.DB.prepare('SELECT * FROM users WHERE id=?').bind(u.id).first();return json({user:safeUser(fresh),...(x.token?{token:fresh.token}:{})})}
if(p==='/users/hot'&&m==='GET'){const r=await e.DB.prepare('SELECT u.username,u.avatar,u.honor_year,u.honor_rank,u.school,SUM(p.views+p.likes*5+p.comments_count*10) AS total_heat FROM users u JOIN posts p ON u.username=p.author GROUP BY u.username ORDER BY total_heat DESC').all();return json({users:r.results||[]})}
const pub=p.match(/^\/users\/([^/]+)$/);if(pub&&m==='GET'){const n=decodeURIComponent(pub[1]);if(n==='me')return json({error:'Not found'},404);const u=await e.DB.prepare('SELECT username,avatar,school,honor_year,honor_rank FROM users WHERE username=?').bind(n).first();if(!u)return json({error:'User not found'},404);const posts=await e.DB.prepare('SELECT id,title,views,likes,comments_count,created_at FROM posts WHERE author=? ORDER BY created_at DESC').bind(n).all();return json({user:u,posts:posts.results||[]})}
if(p==='/posts'&&m==='GET'){const s=(url.searchParams.get('search')||'').slice(0,200),r=await e.DB.prepare('SELECT p.*,u.avatar,(p.views+p.likes*5+p.comments_count*10) AS heat_score FROM posts p LEFT JOIN users u ON p.author=u.username WHERE p.title LIKE ? ORDER BY heat_score DESC,p.created_at DESC').bind('%'+s+'%').all();return json({posts:r.results||[]})}
if(p==='/posts'&&m==='POST'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const b=await req.json(),title=String(b.title||'').trim(),content=String(b.content_md||'').trim();if(!title||!content)return json({error:'标题或内容不能为空'},400);if(title.length>MAX_TITLE_LENGTH||content.length>MAX_CONTENT_LENGTH)return json({error:'文章长度超限'},400);await e.DB.prepare('INSERT INTO posts (title,content_md,author) VALUES (?,?,?)').bind(title,content,u.username).run();return json({success:true})}
const pm=p.match(/^\/posts\/(\d+)$/);if(pm&&m==='GET'){const id=Number(pm[1]),post=await e.DB.prepare('SELECT * FROM posts WHERE id=?').bind(id).first();if(!post)return json({error:'Not found'},404);await e.DB.prepare('UPDATE posts SET views=views+1 WHERE id=?').bind(id).run();post.views=(post.views||0)+1;post.author_info=await e.DB.prepare('SELECT avatar,school,honor_year,honor_rank FROM users WHERE username=?').bind(post.author).first()||{};const heat=post.views+post.likes*5+post.comments_count*10,next=await e.DB.prepare('SELECT id FROM posts WHERE (views+likes*5+comments_count*10)<? ORDER BY (views+likes*5+comments_count*10) DESC,created_at DESC LIMIT 1').bind(heat).first(),u=await userOf(req,e),liked=!!(u&&await e.DB.prepare('SELECT 1 FROM post_likes WHERE user_id=? AND post_id=?').bind(u.username,id).first());return json({post,next_id:next?.id||null,liked})}
if(pm&&m==='DELETE'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const id=Number(pm[1]),post=await e.DB.prepare('SELECT author FROM posts WHERE id=?').bind(id).first();if(!post)return json({error:'文章不存在'},404);if(post.author!==u.username)return json({error:'无权删除这篇文章'},403);await e.DB.batch([e.DB.prepare('DELETE FROM comments WHERE section=?').bind('blog-'+id),e.DB.prepare('DELETE FROM post_likes WHERE post_id=?').bind(id),e.DB.prepare('DELETE FROM posts WHERE id=?').bind(id)]);return json({success:true,id})}
const pl=p.match(/^\/posts\/(\d+)\/like$/);if(pl&&m==='POST'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const id=Number(pl[1]);if(!await e.DB.prepare('SELECT id FROM posts WHERE id=?').bind(id).first())return json({error:'文章不存在'},404);const liked=await e.DB.prepare('SELECT 1 FROM post_likes WHERE user_id=? AND post_id=?').bind(u.username,id).first();if(liked){await e.DB.batch([e.DB.prepare('DELETE FROM post_likes WHERE user_id=? AND post_id=?').bind(u.username,id),e.DB.prepare('UPDATE posts SET likes=CASE WHEN likes>0 THEN likes-1 ELSE 0 END WHERE id=?').bind(id)]);return json({success:true,action:'unliked'})}await e.DB.batch([e.DB.prepare('INSERT INTO post_likes (user_id,post_id) VALUES (?,?)').bind(u.username,id),e.DB.prepare('UPDATE posts SET likes=likes+1 WHERE id=?').bind(id)]);return json({success:true,action:'liked'})}
if(p==='/comments'&&m==='POST'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const b=await req.json(),section=String(b.section||'').trim(),content=String(b.content||'').trim(),parent=b.parent_id==null||b.parent_id===''?null:Number(b.parent_id);if(!section||!content)return json({error:'评论内容不能为空'},400);if(section.length>200||content.length>MAX_COMMENT_LENGTH||parent!==null&&!Number.isInteger(parent))return json({error:'评论参数无效'},400);if(parent!==null&&!await e.DB.prepare('SELECT id FROM comments WHERE id=? AND section=?').bind(parent,section).first())return json({error:'回复目标不存在'},404);await e.DB.prepare('INSERT INTO comments (section,username,content,parent_id) VALUES (?,?,?,?)').bind(section,u.username,content,parent).run();if(section.startsWith('blog-')&&/^\d+$/.test(section.slice(5)))await e.DB.prepare('UPDATE posts SET comments_count=comments_count+1 WHERE id=?').bind(Number(section.slice(5))).run();return json({success:true})}
if(p==='/comments'&&m==='GET'){const section=(url.searchParams.get('section')||'').slice(0,200);if(!section)return json({error:'Missing section'},400);const r=await e.DB.prepare('SELECT * FROM comments WHERE section=? ORDER BY created_at ASC').bind(section).all(),comments=r.results||[];for(const c of comments){const a=await e.DB.prepare('SELECT avatar FROM users WHERE username=?').bind(c.username).first();c.avatar=a?.avatar||'images/0721.png'}return json({comments,total:comments.length})}
const cd=p.match(/^\/comments\/(\d+)$/);if(cd&&m==='DELETE'){const u=await userOf(req,e);if(!u)return json({error:'未登录'},401);const id=Number(cd[1]),c=await e.DB.prepare('SELECT * FROM comments WHERE id=?').bind(id).first();if(!c)return json({error:'评论不存在'},404);if(c.username!==u.username)return json({error:'无权删除这条评论'},403);await e.DB.prepare('UPDATE comments SET parent_id=? WHERE parent_id=?').bind(c.parent_id||null,id).run();await e.DB.prepare('DELETE FROM comments WHERE id=?').bind(id).run();if(c.section.startsWith('blog-')&&/^\d+$/.test(c.section.slice(5)))await e.DB.prepare('UPDATE posts SET comments_count=CASE WHEN comments_count>0 THEN comments_count-1 ELSE 0 END WHERE id=?').bind(Number(c.section.slice(5))).run();return json({success:true,id})}
const cl=p.match(/^\/comments\/(\d+)\/like$/);if(cl&&m==='POST'){const u=await userOf(req,e);if(!u)return json({error:'请先登录'},401);const id=Number(cl[1]);if(!await e.DB.prepare('SELECT id FROM comments WHERE id=?').bind(id).first())return json({error:'评论不存在'},404);await e.DB.prepare('UPDATE comments SET likes=likes+1 WHERE id=?').bind(id).run();const x=await e.DB.prepare('SELECT likes FROM comments WHERE id=?').bind(id).first();return json({likes:x?.likes||0})}
if(p==='/api/chat'&&m==='POST'){if(!await userOf(req,e))return json({error:'请先登录'},401);return chat(await req.json(),e)}
if(p==='/api/history'||p.startsWith('/api/history/')){const u=await userOf(req,e);if(!u)return json({error:'Unauthorized'},401);return history(req,e,u,p,m)}
return json({error:'Not found'},404)
}catch(err){console.error(err);return json({error:err?.message||'Internal Server Error'},500)}}};
