const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json; charset=utf-8",...CORS}});
const token=r=>(r.headers.get("Authorization")||"").replace(/^Bearer\s+/,"").trim();
async function user(r,e){const t=token(r);return t?e.DB.prepare("SELECT * FROM users WHERE token=?").bind(t).first():null}
function safe(u){if(!u)return null;const {password,token,...x}=u;return x}
async function auth(r,e){const u=await user(r,e);if(!u)throw Object.assign(new Error("未登录"),{status:401});return u}
function fail(e){return json({error:e?.message||"Internal Server Error"},e?.status||500)}
function bodyAnswers(a){if(!Array.isArray(a))return null;return a.filter(x=>typeof x==="string"&&/^[ABCD]$/.test(x))}
async function schools(e){const r=await e.DB.prepare("SELECT id,name,created_at FROM schools ORDER BY name").all();return json({schools:r.results||[]})}
async function exams(r,e,u){const q=u.role==="coach"?"SELECT e.*,p.code,p.title paper_title FROM exams e JOIN papers p ON p.id=e.paper_id WHERE e.school_id=? OR e.kind='inter_school' ORDER BY e.created_at DESC":"SELECT DISTINCT e.*,p.code,p.title paper_title FROM exams e JOIN papers p ON p.id=e.paper_id LEFT JOIN exam_schools es ON es.exam_id=e.id WHERE (e.school_id=? OR es.school_id=?) AND e.status<>'draft' ORDER BY e.created_at DESC";const args=u.role==="coach"?[u.school_id]:[u.school_id,u.school_id];const x=await e.DB.prepare(q).bind(...args).all();return json({exams:x.results||[]})}
async function exam(r,e,u,id){const x=await e.DB.prepare("SELECT e.*,p.code,p.title paper_title,p.source_url,p.document_type FROM exams e JOIN papers p ON p.id=e.paper_id WHERE e.id=?").bind(id).first();if(!x)throw Object.assign(new Error("考试不存在"),{status:404});if(u.role==="student"){const allowed=await e.DB.prepare("SELECT 1 FROM exam_schools WHERE exam_id=? AND school_id=?").bind(id,u.school_id).first();if(x.school_id!==u.school_id&&x.kind!=="inter_school"&&!allowed)throw Object.assign(new Error("无权访问"),{status:403})}const qs=await e.DB.prepare("SELECT id,public_id,number,stem,ocr_text,solution,difficulty,question_type,source FROM questions WHERE paper_id=? ORDER BY number").bind(x.paper_id).all();return json({exam:x,questions:qs.results||[]})}
async function start(r,e,u,id){const ex=await e.DB.prepare("SELECT * FROM exams WHERE id=?").bind(id).first();if(!ex)throw Object.assign(new Error("考试不存在"),{status:404});if(ex.status==="closed"||new Date(ex.deadline)<=new Date())throw Object.assign(new Error("考试已截止"),{status:409});let s=await e.DB.prepare("SELECT * FROM submissions WHERE exam_id=? AND student_id=?").bind(id,u.id).first();if(!s){await e.DB.prepare("INSERT INTO submissions(exam_id,student_id) VALUES(?,?)").bind(id,u.id).run();s=await e.DB.prepare("SELECT * FROM submissions WHERE exam_id=? AND student_id=?").bind(id,u.id).first()}const a=await e.DB.prepare("SELECT question_id,answer_json FROM answers WHERE submission_id=?").bind(s.id).all();return json({submission:s,answers:a.results||[]})}
async function save(r,e,u,id){const s=await e.DB.prepare("SELECT s.*,x.deadline FROM submissions s JOIN exams x ON x.id=s.exam_id WHERE s.id=? AND s.student_id=?").bind(id,u.id).first();if(!s)throw Object.assign(new Error("答卷不存在"),{status:404});if(s.status!=="draft"||new Date(s.deadline)<=new Date())throw Object.assign(new Error("答卷已锁定"),{status:409});const b=await r.json();const answers=Array.isArray(b.answers)?b.answers:[];const rev=Number(b.revision)||0;const stmts=[];for(const a of answers){const opts=bodyAnswers(a.answer);if(!opts)continue;stmts.push(e.DB.prepare("INSERT INTO answers(submission_id,question_id,answer_json) VALUES(?,?,?) ON CONFLICT(submission_id,question_id) DO UPDATE SET answer_json=excluded.answer_json,updated_at=CURRENT_TIMESTAMP").bind(id,Number(a.question_id),JSON.stringify(opts)))}if(stmts.length)await e.DB.batch(stmts);await e.DB.prepare("UPDATE submissions SET local_revision=MAX(local_revision,?) WHERE id=?").bind(rev,id).run();return json({success:true,revision:Math.max(rev,s.local_revision||0)})}
async function submit(r,e,u,id){const s=await e.DB.prepare("SELECT s.*,x.deadline FROM submissions s JOIN exams x ON x.id=s.exam_id WHERE s.id=? AND s.student_id=?").bind(id,u.id).first();if(!s)throw Object.assign(new Error("答卷不存在"),{status:404});if(s.status!=="draft")return json({success:true,status:s.status});await e.DB.prepare("UPDATE submissions SET status='submitted',submitted_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();return json({success:true,status:"submitted"})}
async function questions(e){const x=await e.DB.prepare("SELECT q.*,p.code paper_code,p.title paper_title FROM questions q LEFT JOIN papers p ON p.id=q.paper_id ORDER BY q.created_at DESC LIMIT 500").all();return json({questions:x.results||[]})}
async function comments(r,e,u,qid){if(r.method==="GET"){const x=await e.DB.prepare("SELECT c.id,c.content,c.hidden,c.created_at,u.username,u.school_id FROM question_comments c JOIN users u ON u.id=c.user_id WHERE c.question_id=? ORDER BY c.created_at").bind(qid).all();return json({comments:x.results||[]})}const b=await r.json();const content=String(b.content||"").trim();if(!content)throw Object.assign(new Error("评论不能为空"),{status:400});await e.DB.prepare("INSERT INTO question_comments(question_id,user_id,content) VALUES(?,?,?)").bind(qid,u.id,content).run();return json({success:true})}
async function versions(e,id){const x=await e.DB.prepare("SELECT id,version,answer_key_version_id,scoring_rule_json,is_current,created_at FROM score_versions WHERE exam_id=? ORDER BY version DESC").bind(id).all();return json({versions:x.results||[]})}
export default{async fetch(r,e){if(r.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});try{const p=new URL(r.url).pathname;if(p==="/login"&&r.method==="POST"){const b=await r.json();const u=await e.DB.prepare("SELECT * FROM users WHERE username=?").bind(String(b.username||"").trim()).first();if(!u)throw Object.assign(new Error("账号或密码错误"),{status:401});const {sha256}=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(String(b.password||"")));return fail(new Error("请将现有 Worker 的密码校验逻辑接入此认证入口"))}const u=await auth(r,e);if(p==="/users/me"&&r.method==="GET")return json({user:safe(u)});if(p==="/api/schools")return schools(e);if(p==="/api/exams"&&r.method==="GET")return exams(r,e,u);let m=p.match(/^\/api\/exams\/(\d+)$/);if(m&&r.method==="GET")return exam(r,e,u,+m[1]);m=p.match(/^\/api\/exams\/(\d+)\/submission$/);if(m&&r.method==="POST")return start(r,e,u,+m[1]);m=p.match(/^\/api\/submissions\/(\d+)\/answers$/);if(m&&r.method==="PUT")return save(r,e,u,+m[1]);m=p.match(/^\/api\/submissions\/(\d+)\/submit$/);if(m&&r.method==="POST")return submit(r,e,u,+m[1]);if(p==="/api/questions"&&r.method==="GET")return questions(e);m=p.match(/^\/api\/questions\/(\d+)\/comments$/);if(m)return comments(r,e,u,+m[1]);m=p.match(/^\/api\/exams\/(\d+)\/score-versions$/);if(m&&r.method==="GET")return versions(e,+m[1]);throw Object.assign(new Error("Not found"),{status:404})}catch(e){return fail(e)}}};